name = "gleamish_extlib"
version = "0.3.0"

licences = ["Apache-2.0"]
description = "A community driven extended standard library for Gleam"
repository = { type = "github", user = "inoas", repo = "gleamish_extlib" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.26"

[dev-dependencies]
glacier = "~> 0.6.2"
glychee = "~> 0.2"

# Generated JavaScript specific configuration (optional)
[javascript]
# Generate TypeScript .d.ts files
typescript_declarations = true

[javascript.deno]
allow_read = ["./"]
allow_run = ["gleam"]

[documentation]
pages = [
	{ title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
	{ title = "LICENSE", path = "license.html", source = "LICENSE" },
]
